# .github/release.yml
# Configuration for GitHub automated release notes
# Documentation: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - "skip-changelog"

  categories:
    - title: "✨ New Features"
      labels:
        - "feature"
        - "enhancement"

    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bugfix"
        - "bug"

    - title: "🌐 Translations"
      labels:
        - "translation"

    - title: "📦 Dependencies"
      labels:
        - "dependency"

    - title: "🧹 Code Quality and Maintenance"
      labels:
        - "maintenance"
        - "code quality"

    - title: "🔧 Development Environment and Tools"
      labels:
        - "dev tools"

    - title: "📝 Other Changes"
      labels:
        - "*"
      exclude:
        labels:
          - "feature"
          - "enhancement"
          - "fix"
          - "bugfix"
          - "bug"
          - "translation"
          - "dependency"
          - "maintenance"
          - "code quality"
          - "dev tools"
          - "skip-changelog"
